### ISSUE TITLE
Criação de Protótipos de Baixa Fidelidade

### ISSUE THREAD

**Issue by jonabergamo** [jonabergamo/changelog-generator-gui#2]
### Link de visualização do figma

Changelog Generator project

[Link](https://www.figma.com/design/PHYiyI1odoaLBmSjzvjVHt/Materia-Gestao-de-Projetos?node-id=48-437&t=SEJVORDDcEg89pZN-1)

**Comment by GustaOlivr** [comment]
No pente!
